### ISSUE TITLE
The configure consortium maintainer screen hangs on submission

### ISSUE THREAD

**Issue by oneofadrew** [neelix-io/neelix-experiences#12]
Steps to recreate:

- I logged on to create a new account using Google SSO (drew@***********.net.au).
- On the home screen I was presented with a select consortium / switch journals screen.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/5185863/184536393-57e2d65c-7ac8-4284-b162-4e19a0be5293.png">

- I choose the create new space option and accepted the 45 day free trial, then was presented with a "Welcome" screen
- I accepted the default language of english and went on to billing
- I clicked the "+" next to the empty pick list and was presented with the screen titled "This screen is for configuring who will maintain the consortium."
- I filled out the details for a business and then clicked create.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5185863/184536724-d6e8ced6-ff03-4f51-a0dd-70099f02f024.png">
(email address has been changed)

**Expected**: the consortium to be created and the "welcome" screen to be shown with the new consortium selected in the pick list.
**Actual**: the screen froze with the create button greyed out with the spinner continuing to spin.

The behaviour seems reproducible for me - I attempted the actions twice with the same steps and received the same outcome.

**Comment by neelix-admin** [comment]
Thank you for the report. We found the issue and it is now rectified. Huge apologies for inconvenience.

What caused the issue:
- You billing entity was not being created because of the validation in the backend that is checking if the business client entity is unique
- The root cause of the issue was in the logic of the validation because it was too broad in its implementation checked details
