### ISSUE TITLE
Slack app account pairing - requiring user to have admin priviliges to the space

### ISSUE THREAD

**Issue by yoda-da** [neelix-io/neelix-experiences#5]
Issue : User cannot pair the account because process requires admin privileges on Slack space

Description:

- Admin User A logged in , linked their account, and connected integration
- Our clack space is showing neelix commands successfully
- User B, who is not admin, went to slack > clicked on link account > landed on the page that shows following message
`
You are not authorized to install Neelix Team for Slack on {Our Slack Space}
Neelix Team for Slack is restricted for this workspace. Please reach out to one of your App Managers if you would like additional information or to ask them to install this app.
`
- Why does user B handshake require admin privileges on the space?

**Comment by neelix-admin** [comment]
Thank you for report. We are investigating.

**Comment by neelix-admin** [comment]
The issue was encountered for the scenario where workspace configuration disallows linking Neelix and Slack user account by the means of Slack authentication. We implemented necessary enhancement to cater for such configuration.

**Comment by neelix-admin** [comment]
Root cause of the issue was due to us not obtaining full list of existing channels in Slack workspace, and us enforcing sing in with slack option for account pairing. This is now improved and retested. On-boarding instructions for non-admin users are expanded to explain a scenario for workspace with restricted sing in options : https://www.neelix.team/team-journal-integration-with-slack
